# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 09:14
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroPoblado',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código centro poblado')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre centro poblado')),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=32718, verbose_name='Geometria')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Ubigeo INEI')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre departamento')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32718, verbose_name='Geometria')),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Ubigeo INEI')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre distrito')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32718, verbose_name='Geometria')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Ubigeo INEI')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre provincia')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32718, verbose_name='Geometria')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubigeo.Departamento', verbose_name='Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Perimetro',
            fields=[
                ('centro_poblado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ubigeo.CentroPoblado', verbose_name='Centro poblado')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=32718, verbose_name='Geometria')),
            ],
        ),
        migrations.AddField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubigeo.Provincia', verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='centropoblado',
            name='distrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubigeo.Distrito', verbose_name='Distrito'),
        ),
    ]
