# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 19:42
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroPoblado',
            fields=[
                ('codigo', models.CharField(help_text='Código del centro poblado', max_length=3, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Debe ingresar tres dígitos.', regex='^[0-9]{3}$')], verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre del centro poblado', max_length=100, verbose_name='Nombre')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(help_text='Geometría asociada al centro poblado, (WKT, EPSG:32718)', srid=32718, verbose_name='Geometría')),
                ('_centroid', django.contrib.gis.db.models.fields.PointField(srid=32718)),
                ('_creado', models.DateTimeField(auto_now_add=True)),
                ('_modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'centros poblados',
                'ordering': ('nombre',),
                'verbose_name': 'centro poblado',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigo', models.CharField(help_text='Ubigeo según INEI', max_length=2, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Debe ingresar dos dígitos.', regex='^[0-9]{2}$')], verbose_name='Ubigeo')),
                ('nombre', models.CharField(help_text='Nombre del departamento', max_length=50, verbose_name='Nombre')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(help_text='Geometría asociada al departamento, (WKT, EPSG:32718)', srid=32718, verbose_name='Geometría')),
                ('_centroid', django.contrib.gis.db.models.fields.PointField(srid=32718)),
                ('_creado', models.DateTimeField(auto_now_add=True)),
                ('_modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('codigo', models.CharField(help_text='Ubigeo según INEI', max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Debe ingresar seis dígitos.', regex='^[0-9]{6}$')], verbose_name='Ubigeo')),
                ('nombre', models.CharField(help_text='Nombre del distrito', max_length=100, verbose_name='Nombre')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(help_text='Geometría asociada al distrito, (WKT, EPSG:32718)', srid=32718, verbose_name='Geometría')),
                ('_centroid', django.contrib.gis.db.models.fields.PointField(srid=32718)),
                ('_creado', models.DateTimeField(auto_now_add=True)),
                ('_modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('codigo', models.CharField(help_text='Ubigeo según INEI', max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Debe ingresar cuatro dígitos.', regex='^[0-9]{4}$')], verbose_name='Ubigeo')),
                ('nombre', models.CharField(help_text='Nombre de la provincia', max_length=100, verbose_name='Nombre')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(help_text='Geometría asociada a la provincia, (WKT, EPSG:32718)', srid=32718, verbose_name='Geometría')),
                ('_centroid', django.contrib.gis.db.models.fields.PointField(srid=32718)),
                ('_creado', models.DateTimeField(auto_now_add=True)),
                ('_modificado', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(help_text='Departamento al que pertenece la provincia', on_delete=django.db.models.deletion.CASCADE, to='ubigeo.Departamento', verbose_name='Departamento')),
            ],
        ),
        migrations.AddField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(help_text='Provincia a la que pertenece el distrito', on_delete=django.db.models.deletion.CASCADE, to='ubigeo.Provincia', verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='centropoblado',
            name='distrito',
            field=models.ForeignKey(help_text='Distrito al que pertenece el centro poblado', on_delete=django.db.models.deletion.CASCADE, to='ubigeo.Distrito', verbose_name='Distrito'),
        ),
    ]
