# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubigeo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centropoblado',
            options={'ordering': ('nombre',), 'verbose_name': 'centro poblado', 'verbose_name_plural': 'centros poblados'},
        ),
    ]
