# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 17:47
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubigeo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centropoblado',
            name='_centroid',
        ),
        migrations.AlterField(
            model_name='centropoblado',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Geometría asociada al centro poblado, (WKT, EPSG:32718)', srid=32718, verbose_name='Geometría'),
        ),
    ]
