# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubigeo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perimetro',
            name='centro_poblado',
        ),
        migrations.DeleteModel(
            name='Perimetro',
        ),
    ]
