# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubigeo', '0003_auto_20161213_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centropoblado',
            old_name='acceso',
            new_name='modificado',
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='acceso',
            new_name='modificado',
        ),
        migrations.RenameField(
            model_name='distrito',
            old_name='acceso',
            new_name='modificado',
        ),
        migrations.RenameField(
            model_name='perimetro',
            old_name='acceso',
            new_name='modificado',
        ),
        migrations.RenameField(
            model_name='provincia',
            old_name='acceso',
            new_name='modificado',
        ),
    ]
