# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 14:56
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubigeo', '0004_auto_20161213_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centropoblado',
            name='codigo',
            field=models.CharField(help_text='Código del centro poblado', max_length=3, primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='centropoblado',
            name='distrito',
            field=models.ForeignKey(help_text='Distrito al que pertenece el centro poblado', on_delete=django.db.models.deletion.CASCADE, to='ubigeo.Distrito', verbose_name='Distrito'),
        ),
        migrations.AlterField(
            model_name='centropoblado',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(help_text='Geometria asociada al centro poblado', srid=32718, verbose_name='Geometria'),
        ),
        migrations.AlterField(
            model_name='centropoblado',
            name='nombre',
            field=models.CharField(help_text='Nombre del centro poblado', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='codigo',
            field=models.CharField(help_text='Ubigeo según INEI', max_length=2, primary_key=True, serialize=False, verbose_name='Ubigeo'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(help_text='Geometria asociada al departamento', srid=32718, verbose_name='Geometria'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(help_text='Nombre del departamento', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='codigo',
            field=models.CharField(help_text='Ubigeo según INEI', max_length=6, primary_key=True, serialize=False, verbose_name='Ubigeo'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(help_text='Geometria asociada al distrito', srid=32718, verbose_name='Geometria'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='nombre',
            field=models.CharField(help_text='Nombre del distrito', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(help_text='Provincia a la que pertenece el distrito', on_delete=django.db.models.deletion.CASCADE, to='ubigeo.Provincia', verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='perimetro',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(help_text='Geometria asociada al centro poblado', srid=32718, verbose_name='Geometria'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='codigo',
            field=models.CharField(help_text='Ubigeo según INEI', max_length=4, primary_key=True, serialize=False, verbose_name='Ubigeo'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='departamento',
            field=models.ForeignKey(help_text='Departamento al que pertenece la provincia', on_delete=django.db.models.deletion.CASCADE, to='ubigeo.Departamento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(help_text='Geometria asociada a la provincia', srid=32718, verbose_name='Geometria'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(help_text='Nombre de la provincia', max_length=100, verbose_name='Nombre'),
        ),
    ]
