# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubigeo', '0006_auto_20161213_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centropoblado',
            options={'ordering': ('nombre',), 'verbose_name': 'Centro poblado', 'verbose_name_plural': 'Centros poblados'},
        ),
    ]
