# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOficio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la ocupación / oficio / profesión', max_length=50, verbose_name='Nombre')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tipo de oficio',
                'ordering': ('nombre',),
                'verbose_name_plural': 'tipos de oficio',
            },
        ),
        migrations.CreateModel(
            name='TipoProductoAgricola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del producto agricola', max_length=50, verbose_name='Nombre')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tipo de producto agricola',
                'ordering': ('nombre',),
                'verbose_name_plural': 'tipos de producto agricola',
            },
        ),
        migrations.CreateModel(
            name='TipoProductoDestino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del destino del producto', max_length=50, verbose_name='Nombre')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tipo de destino de producto',
                'ordering': ('nombre',),
                'verbose_name_plural': 'tipos de destino de producto',
            },
        ),
        migrations.CreateModel(
            name='TipoUnidadMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la unidad de medida', max_length=50, verbose_name='Nombre')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tipo de unidad de medida',
                'ordering': ('nombre',),
                'verbose_name_plural': 'tipos de unidades de medida',
            },
        ),
    ]
