# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CentroTrabajo',
            new_name='TipoCentroTrabajo',
        ),
        migrations.RenameModel(
            old_name='Oficio',
            new_name='TipoOficio',
        ),
    ]
