# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20161213_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipocentrotrabajo',
            options={'verbose_name': 'tipo centro de trabajo', 'verbose_name_plural': 'tipos de centro de trabajo'},
        ),
        migrations.AlterModelOptions(
            name='tipooficio',
            options={'verbose_name': 'tipo de oficio', 'verbose_name_plural': 'tipos de oficio'},
        ),
    ]
