# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20161215_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProductoPecuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del producto pecuario', max_length=50, verbose_name='Nombre')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tipo de producto pecuario',
                'verbose_name_plural': 'tipos de producto pecuario',
                'ordering': ('nombre',),
            },
        ),
    ]
