# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_auto_20161220_1048'),
        ('item', '0004_delete_tipoproductopecuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoCentroTrabajo',
        ),
    ]
