# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 10:37
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubigeo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manzana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código de la manzana', max_length=3, validators=[django.core.validators.RegexValidator(message='Debe ingresar tres dígitos.', regex='^[0-9]{3}$')], verbose_name='Código')),
                ('letra', models.CharField(help_text='Letra de la manzana', max_length=3, validators=[django.core.validators.RegexValidator(message='Debe ingresar tres dígitos.', regex='^[A-Za-z0-9]{3}$')], verbose_name='Letra')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(help_text='Geometría asociada a la manzana, (WKT, EPSG:32718)', srid=32718, verbose_name='Geometría')),
                ('_centroid', django.contrib.gis.db.models.fields.PointField(srid=32718)),
                ('_creado', models.DateTimeField(auto_now_add=True)),
                ('_modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('codigo',),
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código del sector', max_length=2, validators=[django.core.validators.RegexValidator(message='Debe ingresar dos dígitos.', regex='^[0-9]{2}$')], verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre del sector', max_length=100, verbose_name='Nombre')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(help_text='Geometría asociada al sector, (WKT, EPSG:32718)', srid=32718, verbose_name='Geometría')),
                ('_centroid', django.contrib.gis.db.models.fields.PointField(srid=32718)),
                ('_creado', models.DateTimeField(auto_now_add=True)),
                ('_modificado', models.DateTimeField(auto_now=True)),
                ('centro_poblado', models.ForeignKey(help_text='Centro poblado al que pertenece el sector', on_delete=django.db.models.deletion.CASCADE, to='ubigeo.CentroPoblado', verbose_name='Centro Poblado')),
            ],
            options={
                'verbose_name': 'sector',
                'verbose_name_plural': 'sectores',
                'ordering': ('codigo',),
            },
        ),
        migrations.AddField(
            model_name='manzana',
            name='sector',
            field=models.ForeignKey(help_text='Sector al que pertenece la manzana', on_delete=django.db.models.deletion.CASCADE, to='catastro.Sector', verbose_name='Sector'),
        ),
        migrations.AlterUniqueTogether(
            name='sector',
            unique_together=set([('codigo', 'centro_poblado')]),
        ),
        migrations.AlterUniqueTogether(
            name='manzana',
            unique_together=set([('codigo', 'letra')]),
        ),
    ]
