# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 12:19
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubigeo', '0002_auto_20170410_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perimetro',
            fields=[
                ('centro_poblado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ubigeo.CentroPoblado', verbose_name='Centro poblado')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(help_text='Geometria asociada al centro poblado', srid=32718, verbose_name='Geometria')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
