# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manzana',
            name='letra',
            field=models.CharField(default='', help_text='Letra de la manzana', max_length=3, verbose_name='Letra'),
            preserve_default=False,
        ),
    ]
