# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 16:04
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manzana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código de la manzana', max_length=3, validators=[django.core.validators.RegexValidator(message='Debe ingresar tres dígitos.', regex='^[0-9]{3}$')], verbose_name='Código')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(help_text='Geometría asociada a la manzana, (WKT, EPSG:32718)', srid=32718, verbose_name='Geometría')),
                ('_centroid', django.contrib.gis.db.models.fields.PointField(srid=32718)),
                ('_creado', models.DateTimeField(auto_now_add=True)),
                ('_modificado', models.DateTimeField(auto_now=True)),
                ('sector', models.ForeignKey(help_text='Sector al que pertenece la manzana', on_delete=django.db.models.deletion.CASCADE, to='catastro.Sector', verbose_name='Sector')),
            ],
            options={
                'verbose_name': 'sector',
                'ordering': ('codigo',),
                'verbose_name_plural': 'sectores',
            },
        ),
        migrations.AlterUniqueTogether(
            name='manzana',
            unique_together=set([('codigo', 'sector')]),
        ),
    ]
