# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0002_auto_20170424_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manzana',
            options={'ordering': ('codigo',)},
        ),
    ]
