# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 15:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_persona', models.PositiveSmallIntegerField(choices=[(1, 'NATURAL'), (2, 'JURIDICA')])),
                ('tipo_documento', models.PositiveSmallIntegerField(choices=[(2, 'DNI'), (9, 'RUC'), (1, 'SIN DOCUMENTO')])),
                ('nro_documento', models.CharField(help_text='Nro de documento de la persona', max_length=11, validators=[django.core.validators.RegexValidator(message='Debe ingresar un documento válido.', regex='^[0-9]{8,11}$')], verbose_name='Nro Documento')),
                ('nombre', models.CharField(help_text='Nombre o razón social', max_length=100, verbose_name='Nombre')),
                ('_creado', models.DateTimeField(auto_now_add=True)),
                ('_modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('nro_documento',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='persona',
            unique_together=set([('nro_documento',)]),
        ),
    ]
