# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='tipo_documento',
            field=models.PositiveSmallIntegerField(choices=[(2, 'DNI'), (9, 'RUC')]),
        ),
    ]
