# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 08:12
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubigeo', '0001_initial'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje de habitantes que laboran en el centro de trabajo', max_digits=5, validators=(django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))), verbose_name='Porcentaje')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'centro de trabajo',
                'verbose_name_plural': 'centros de trabajo',
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('centro_poblado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ubigeo.CentroPoblado', verbose_name='Centro poblado')),
                ('nro_habitantes', models.PositiveIntegerField(help_text='Total nro de habitantes del centro poblado', verbose_name='Nro de habitantes')),
                ('nro_familias', models.PositiveIntegerField(help_text='Total nro de familias del centro poblado', verbose_name='Nro de familias')),
                ('m200', models.PositiveIntegerField(help_text='Nro de familias con ingresos económicos iguales o menores a 200 Soles al mes', verbose_name='Igual ó menor a 200 Soles')),
                ('m201_499', models.PositiveIntegerField(help_text='Nro de familias con ingresos económicos de 201 a 499 Soles al mes', verbose_name='De 201 a 499 Soles')),
                ('m501_999', models.PositiveIntegerField(help_text='Nro de familias con ingresos económicos de 500 a 999 Soles al mes', verbose_name='De 500 a 999 Soles')),
                ('m1000', models.PositiveIntegerField(help_text='Nro de familias con ingresos económicos iguales o mayores a 1000 Soles al mes', verbose_name='Igual ó mayor a 1000 Soles')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje de habitantes que ejercen la ocupación / oficio / profesión', max_digits=5, validators=(django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))), verbose_name='Porcentaje')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('centro_poblado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubigeo.CentroPoblado', verbose_name='Centro poblado')),
                ('tipo_oficio', models.ForeignKey(help_text='Tipo de ocupación / oficio / profesión', on_delete=django.db.models.deletion.CASCADE, to='item.TipoOficio', verbose_name='Ocupación')),
            ],
            options={
                'verbose_name': 'Oficio',
                'verbose_name_plural': 'Oficios',
            },
        ),
        migrations.AddField(
            model_name='centrotrabajo',
            name='centro_poblado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubigeo.CentroPoblado', verbose_name='Centro poblado'),
        ),
        migrations.AddField(
            model_name='centrotrabajo',
            name='tipo_centro_trabajo',
            field=models.ForeignKey(help_text='Tipo de centro de trabajo', on_delete=django.db.models.deletion.CASCADE, to='item.TipoCentroTrabajo', verbose_name='Centro de labor'),
        ),
        migrations.AlterUniqueTogether(
            name='oficio',
            unique_together=set([('centro_poblado', 'tipo_oficio')]),
        ),
        migrations.AlterUniqueTogether(
            name='centrotrabajo',
            unique_together=set([('centro_poblado', 'tipo_centro_trabajo')]),
        ),
    ]
