# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubigeo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('centro_poblado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ubigeo.CentroPoblado', verbose_name='Centro poblado')),
                ('nro_personas', models.PositiveIntegerField(verbose_name='Nro de habitantes')),
                ('nro_familias', models.PositiveIntegerField(verbose_name='Nro de familias')),
                ('m200', models.PositiveIntegerField(verbose_name='Menor a 200 Soles')),
                ('m201_500', models.PositiveIntegerField(verbose_name='De 201 a 499 Soles')),
                ('m501_1000', models.PositiveIntegerField(verbose_name='De 500 a 999 Soles')),
                ('m1001', models.PositiveIntegerField(verbose_name='Mayor a 1000 Soles')),
            ],
        ),
    ]
