# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 08:16
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubigeo', '0001_initial'),
        ('item', '0002_auto_20161215_0816'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agricola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(help_text='Nro de unidades de producto, producidas por año', verbose_name='Cantidad')),
                ('promedio_precio_venta', models.DecimalField(decimal_places=2, help_text='Promedio de precio de venta del producto', max_digits=8, validators=(django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100000.00'))), verbose_name='Promedio PV')),
                ('promedio_precio_real_venta', models.DecimalField(decimal_places=2, help_text='Promedio de precio de venta del producto, en el mercado local', max_digits=8, validators=(django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100000.00'))), verbose_name='Promedio PRV')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('centro_poblado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubigeo.CentroPoblado', verbose_name='Centro poblado')),
                ('destino', models.ForeignKey(help_text='Destino / finalidad del producto', on_delete=django.db.models.deletion.CASCADE, to='item.TipoProductoDestino', verbose_name='Destino')),
                ('tipo', models.ForeignKey(help_text='Tipo de producto agricola', on_delete=django.db.models.deletion.CASCADE, to='item.TipoProductoAgricola', verbose_name='Producto')),
                ('unidad_medida', models.ForeignKey(help_text='Unidad de medida del producto', on_delete=django.db.models.deletion.CASCADE, to='item.TipoUnidadMedida', verbose_name='Unidad medida')),
            ],
            options={
                'verbose_name': 'Oficio',
                'verbose_name_plural': 'Oficios',
            },
        ),
        migrations.AlterUniqueTogether(
            name='agricola',
            unique_together=set([('centro_poblado', 'tipo')]),
        ),
    ]
