# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingreso',
            old_name='nro_personas',
            new_name='nro_habitantes',
        ),
    ]
