# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20161215_0816'),
        ('ubigeo', '0001_initial'),
        ('social', '0002_auto_20161215_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agricola',
            old_name='tipo',
            new_name='producto',
        ),
        migrations.AlterUniqueTogether(
            name='agricola',
            unique_together=set([('centro_poblado', 'producto')]),
        ),
    ]
