# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20161213_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingreso',
            old_name='m201_500',
            new_name='m201_499',
        ),
        migrations.RenameField(
            model_name='ingreso',
            old_name='m501_1000',
            new_name='m501_999',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='m1001',
        ),
        migrations.AddField(
            model_name='ingreso',
            name='m1000',
            field=models.PositiveIntegerField(default=0, verbose_name='Mayor ó igual a 1000 Soles'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='m200',
            field=models.PositiveIntegerField(verbose_name='Igual ó Menor a 200 Soles'),
        ),
    ]
