# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 19:18
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20161213_1918'),
        ('ubigeo', '0007_auto_20161213_1918'),
        ('social', '0002_auto_20161213_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje de habitantes que ejercen la ocupación / oficio / profesión', max_digits=5, validators=(django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))), verbose_name='Porcentaje')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('centro_poblado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubigeo.CentroPoblado', verbose_name='Centro poblado')),
                ('tipo_oficio', models.ForeignKey(help_text='Tipo de ocupación / oficio / profesión', on_delete=django.db.models.deletion.CASCADE, to='item.TipoOficio', verbose_name='Ocupación')),
            ],
            options={
                'verbose_name_plural': 'Oficios',
                'verbose_name': 'Oficio',
            },
        ),
        migrations.AlterField(
            model_name='centrotrabajo',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje de habitantes que laboran en el centro de trabajo', max_digits=5, validators=(django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))), verbose_name='Porcentaje'),
        ),
        migrations.AlterUniqueTogether(
            name='oficio',
            unique_together=set([('centro_poblado', 'tipo_oficio')]),
        ),
    ]
