# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20161213_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='centro_poblado',
            field=models.OneToOneField(help_text='blablabdfgsd sdfg sdf gs dfg sd t erg sd  f', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ubigeo.CentroPoblado', verbose_name='Centro poblado'),
        ),
    ]
