# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20161215_0820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agricola',
            options={'verbose_name': 'producto agricola', 'verbose_name_plural': 'productos agricolas'},
        ),
    ]
