# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 10:54
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20161215_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agricola',
            name='promedio_precio_real_venta',
            field=models.DecimalField(decimal_places=2, help_text='Promedio de precio de venta del producto, en el mercado local', max_digits=8, validators=(django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100000.00'))), verbose_name='Promedio PRV'),
        ),
        migrations.AlterField(
            model_name='agricola',
            name='promedio_precio_venta',
            field=models.DecimalField(decimal_places=2, help_text='Promedio de precio de venta del producto', max_digits=8, validators=(django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100000.00'))), verbose_name='Promedio PV'),
        ),
    ]
