# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 11:04
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubigeo', '0001_initial'),
        ('item', '0003_tipoproductopecuario'),
        ('social', '0005_auto_20161215_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pecuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(help_text='Nro de unidades de producto, producidas por año', verbose_name='Cantidad')),
                ('promedio_precio_venta', models.DecimalField(decimal_places=2, help_text='Promedio de precio de venta por unidad de producto', max_digits=8, validators=(django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10000.00'))), verbose_name='Promedio PV')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('centro_poblado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubigeo.CentroPoblado', verbose_name='Centro poblado')),
                ('destino', models.ForeignKey(help_text='Destino / finalidad del producto', on_delete=django.db.models.deletion.CASCADE, to='item.TipoProductoDestino', verbose_name='Destino')),
                ('producto', models.ForeignKey(help_text='Tipo de producto pecuario', on_delete=django.db.models.deletion.CASCADE, to='item.TipoProductoPecuario', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'producto pecuario',
                'verbose_name_plural': 'productos pecuarios',
            },
        ),
        migrations.AlterUniqueTogether(
            name='pecuario',
            unique_together=set([('centro_poblado', 'producto')]),
        ),
    ]
