# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20161213_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='acceso',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
