# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20161213_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingreso',
            old_name='acceso',
            new_name='modificado',
        ),
    ]
