# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_auto_20161213_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='m1000',
            field=models.PositiveIntegerField(help_text='Nro de familias con ingresos económicos iguales o mayores a 1000 Soles al mes'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='m200',
            field=models.PositiveIntegerField(help_text='Nro de familias con ingresos económicos iguales o menores a 200 Soles al mes', verbose_name='Igual ó Menor a 200 Soles'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='m201_499',
            field=models.PositiveIntegerField(help_text='Nro de familias con ingresos económicos de 201 a 499 Soles al mes', verbose_name='De 201 a 499 Soles'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='m501_999',
            field=models.PositiveIntegerField(help_text='Nro de familias con ingresos económicos de 500 a 999 Soles al mes', verbose_name='De 500 a 999 Soles'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='nro_familias',
            field=models.PositiveIntegerField(help_text='Total nro de familias del centro poblado', verbose_name='Nro de familias'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='nro_habitantes',
            field=models.PositiveIntegerField(help_text='Total nro de habitantes del centro poblado', verbose_name='Nro de habitantes'),
        ),
    ]
