# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_auto_20161216_1256'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pecuario',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='pecuario',
            name='centro_poblado',
        ),
        migrations.RemoveField(
            model_name='pecuario',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='pecuario',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Pecuario',
        ),
    ]
