# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_auto_20161213_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la ocupación / oficio / profesión', max_length=50, verbose_name='Nombre')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='m1000',
            field=models.PositiveIntegerField(help_text='Nro de familias con ingresos económicos iguales o mayores a 1000 Soles al mes', verbose_name='Igual ó mayor a 1000 Soles'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='m200',
            field=models.PositiveIntegerField(help_text='Nro de familias con ingresos económicos iguales o menores a 200 Soles al mes', verbose_name='Igual ó menor a 200 Soles'),
        ),
    ]
