# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_auto_20161220_1043'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='centrotrabajo',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='centrotrabajo',
            name='centro_poblado',
        ),
        migrations.RemoveField(
            model_name='centrotrabajo',
            name='tipo_centro_trabajo',
        ),
        migrations.DeleteModel(
            name='CentroTrabajo',
        ),
    ]
