# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_centrotrabajo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centrotrabajo',
            options={'verbose_name': 'centro de trabajo', 'verbose_name_plural': 'centros de trabajo'},
        ),
    ]
