# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_auto_20161213_1608'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CentroTrabajo',
        ),
        migrations.DeleteModel(
            name='Oficio',
        ),
    ]
